---
# install_kubeadm/tasks/CentOS_8.yml

#
# kernel modules and sysctl settings
#

- name: 'Create file /etc/sysctl.d/net.ipv4.ip_forward.conf'
  sysctl:
    name: 'net.ipv4.ip_forward'
    value: '1'
    sysctl_file: '/etc/sysctl.d/net.ipv4.ip_forward.conf'
    sysctl_set: 'yes'
    reload: 'no'

- name: 'Load the br_netfilter module'
  modprobe:
    name: 'br_netfilter'
    state: 'present'

- name: 'Load the overlay module'
  modprobe:
    name: 'overlay'
    state: 'present'

- name: 'Create file /etc/sysctl.d/net.bridge.bridge-nf-call-iptables.conf'
  sysctl:
    name: 'net.bridge.bridge-nf-call-iptables'
    value: '1'
    sysctl_file: '/etc/sysctl.d/net.bridge.bridge-nf-call-iptables.conf'
    sysctl_set: 'yes'
    reload: 'no'

- name: 'Create file /etc/sysctl.d/net.bridge.bridge-nf-call-ip6tables.conf'
  sysctl:
    name: 'net.bridge.bridge-nf-call-ip6tables'
    value: '1'
    sysctl_file: '/etc/sysctl.d/net.bridge.bridge-nf-call-ip6tables.conf'
    sysctl_set: 'yes'
    reload: 'no'

- name: 'Create /etc/modules-load.d/kubeadm.conf'
  copy:
    content: |
      br_netfilter
      overlay
    dest: '/etc/modules-load.d/kubeadm.conf'
    owner: '0'
    group: '0'
    mode: '0644'

#
# Disable selinux
#
- name: 'Disable selinux'
  ansible.builtin.lineinfile:
    path: '/etc/selinux/config'
    regexp: '^SELINUX='
    line: 'SELINUX=disabled'
  notify:
    - 'Reboot'
    - 'Wait for the machine(s) to be ready again'

#
# Install packages for kubeadm, kubelet & Co
#

- name: 'Add packages.cloud.google.com repository'
  ansible.builtin.yum_repository:
    name: 'packages.cloud.google.com'
    description: 'packages.cloud.google.com'
    file: 'packages.cloud.google.com'
    baseurl: 'https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64'
    gpgkey: 'https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg'
    state: 'present'

- name: 'Install packages kubelet, kubeadm, kubectl and others'
  package:
    name:
      - kubeadm
      - wget
      - curl
      - iproute-tc
    state: 'present'
  ignore_errors: '{{ ansible_check_mode }}'

- name: 'Enable the kubelet.service'
  service:
    name: 'kubelet.service'
    enabled: 'true'

#
# Install and configure docker-ce
#

- name: 'Remove podman-docker'
  yum:
    name: 'podman-docker'
    state: 'absent'
    autoremove: 'yes'

- name: 'Create /etc/docker/daemon.json'
  copy:
    content: |
      {
        "exec-opts": ["native.cgroupdriver=systemd"],
        "log-driver": "json-file",
        "log-opts": {
          "max-size": "100m"
        },
        "storage-driver": "overlay2"
      }
    dest: '/etc/docker/daemon.json'
    owner: '0'
    group: '0'
    mode: '0644'
  notify:
    - 'Reboot'
    - 'Wait for the machine(s) to be ready again'

- name: 'Add download.docker.com repository'
  ansible.builtin.yum_repository:
    name: 'download.docker.com'
    description: 'download.docker.com'
    file: 'download.docker.com'
    baseurl: 'https://download.docker.com/linux/centos/$releasever/$basearch/stable'
    gpgkey: 'https://download.docker.com/linux/centos/gpg'
    state: 'present'

- name: 'Install docker-ce'
  package:
    name:
      - docker-ce
    state: 'present'
  ignore_errors: '{{ ansible_check_mode }}'

- name: 'Enable the docker.service'
  service:
    name: 'docker.service'
    state: 'started'
    enabled: 'true'
