---
# install_kubeadm/tasks/Debian10_runtime_docker.yml

#
# Install docker
#

- name: 'Add apt-key for download.docker.com'
  ansible.builtin.apt_key:
    url: 'https://download.docker.com/linux/ubuntu/gpg'
    state: 'present'

- name: 'Add download.docker.com repository'
  ansible.builtin.apt_repository:
    repo: 'deb [arch=amd64] https://download.docker.com/linux/debian buster stable'
    state: 'present'
    filename: 'download.docker.com'

- name: 'Install packages'
  package:
    name:
      - docker-ce
      - docker-ce-cli
    state: 'present'
  ignore_errors: '{{ ansible_check_mode }}'
  notify:
    - 'Reboot'
    - "Wait for the machine(s) to be ready again"

- name: 'Create directory /etc/systemd/system/docker.service.d'
  ansible.builtin.file:
    path: '/etc/systemd/system/docker.service.d'
    state: 'directory'
    mode: '0755'
  notify:
    - 'Reboot'
    - "Wait for the machine(s) to be ready again"

- name: 'Create /etc/docker/daemon.json'
  copy:
    content: |
      {
        "exec-opts": ["native.cgroupdriver=systemd"],
        "log-driver": "json-file",
        "log-opts": {
          "max-size": "100m"
        },
        "storage-driver": "overlay2"
      }
    dest: '/etc/docker/daemon.json'
    owner: '0'
    group: '0'
    mode: '0644'
  notify:
    - 'Reboot'
    - "Wait for the machine(s) to be ready again"

- name: 'Start and enable the docker service'
  service:
    name: 'docker.service'
    state: 'started'
    enabled: 'true'
  notify:
    - 'Reboot'
    - "Wait for the machine(s) to be ready again"
