---
# install_kubeadm/tasks/main.yml

- name: "openSUSE Leap 15.x"
  include_tasks: openSUSE_Leap.yml
  when: 'ansible_distribution == "openSUSE Leap" and ansible_distribution_major_version | int == 15'
