---
# install_kubeadm/tasks/main.yml

- name: 'Install patterns-containers-kubeadm on openSUSE 15.x'
  zypper:
    name: 'patterns-containers-kubeadm'
    state: 'present'
    disable_recommends: 'true'

- name: 'Start and enable the crio.service'
  service:
    name: 'crio.service'
    state: 'started'
    enabled: 'true'

- name: 'Enable the kubelet.service'
  service:
    name: 'kubelet.service'
    enabled: 'true'

- name: 'Create file /etc/sysctl.d/net.ipv4.ip_forward.conf'
  sysctl:
    name: 'net.ipv4.ip_forward'
    value: '1'
    sysctl_file: '/etc/sysctl.d/net.ipv4.ip_forward.conf'
    sysctl_set: 'yes'
    reload: 'no'
